### ISSUE TITLE
Summary/Need Your Code Submitted

### ISSUE THREAD

**Issue by karl-project-review** [samquan/intro-data-capstone-biodiversity#1]
I need your actual code in order to do a full review. Based on your presentation, it looks like you arrived at the proper results and came to appropriate conclusions based on those results, and you explained your process and results reasonably clearly. Once you submit your code, we can provide a more complete review. From what you've submitted so far though, it looks like you've done well with this project!

**Comment by samquan** [comment]
Sorry, I originally did it through the learning environment so I thought I didn't have to submit it. I have uploaded a file titled "code" now.

**Comment by karl-project-review** [comment]
Thanks -- I went ahead and gave you a complete review.
